name: GitHub Action do zbudowania obrazu i umieszczeniu go na DockerHub

on:
  push:
    branches: [ master ]

jobs:
  build-push-images:
    name: Budowa i publikacja obrazw na repozytorium
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: QEMU set-up
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile2
          push: true
          tags: |
            svikt02/zadanie1:v1.0
          cache-from: type=registry,ref=svikt02/zadanie1:v1.0
          cache-to: type=registry,ref=svikt02/zadanie1:v1.0,mode=max
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
